// Generated by CoffeeScript 1.10.0
(function() {
  var ISL, i, interval, len, ref, u;

  ISL = require('interskiplist');

  u = ISL["new"]();

  ref = require('../data/unicode-9.0.0-intervals.json');
  for (i = 0, len = ref.length; i < len; i++) {
    interval = ref[i];
    ISL.add(u, interval);
  }

  module.exports = u;

}).call(this);

//# sourceMappingURL=unicode-isl.js.map
